import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./Provider";
import UIProvider from "./NextUIProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <Provider>
          <body className={inter.className}>
            <UIProvider >
            <main className="">
              
            {children}
            </main>
            </UIProvider>
          </body>
        </Provider>
    </html>
  );
}
